name: ML Model Development

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: docker

    steps:
    - name: checkout repository
      uses: actions/checkout@v4

    - name: setup python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10.12

    - name: Install Dependencies
      run: pip install -r requirements.txt

    - name: Test with pytest
      run: pytest train/test_train.py

    - name: Train and evaluate model
      run: python train/train.py

    - name: Build Docker Image
      run: docker build -t api_titanic .

    - name: Login to Docker Hub
      run: echo "${{ secrets.PASSWORD }}" | docker login -u "${{ secrets.USERNAME }}" --password-stdin

    - name: Tag Docker Image
      run: docker tag api_titanic ${{ secrets.USERNAME }}/api_titanic

    - name: Push Docker Image
      run: docker push ${{ secrets.USERNAME }}/api_titanic
    
