name: ML Model Development

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: checkout repository
      uses: actions/checkout@v4

    - name: setup python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10.12

    - name: Install Dependencies
      run: pip install -r requirements.txt

    - name: Test with pytest
      run: pytest test_train.py

    - name: Train and evaluate model
      run: python train/train.py
    
